# Generated by Django 4.0.4 on 2022-06-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('add', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
