# Generated by Django 4.0.4 on 2022-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_dog_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.FloatField(),
        ),
    ]
